// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250426030928_UpdateTypeOfScore2")]
    partial class UpdateTypeOfScore2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hinhthucthanhtoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hinhthucthanhtoans");
                });

            modelBuilder.Entity("Phongtro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayThue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNguoiThue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_hinh_thuc_thanh_toan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_hinh_thuc_thanh_toan");

                    b.ToTable("phongtros");
                });

            modelBuilder.Entity("Phongtro", b =>
                {
                    b.HasOne("Hinhthucthanhtoan", "Hinhthucthanhtoan")
                        .WithMany()
                        .HasForeignKey("id_hinh_thuc_thanh_toan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hinhthucthanhtoan");
                });
#pragma warning restore 612, 618
        }
    }
}
